webprogramming/lecture3/lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    #获取url中，hello/ 后面的字符串，传入到这里的name,而这个name变量会传给greet作为变量。
    path("<str:name>", views.greet, name= "greet"),
    path('martin', views.martin, name="martin"),
]

webprogramming/lecture3/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

webprogramming/lecture3/lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
]

webprogramming/lecture3/lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
]

webprogramming/lecture3/lecture3/tasks/models.py
from django.db import models

# Create your models here.

webprogramming/lecture3/lecture3/hello/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def greet(request,name):
    #return HttpResponse(f"Hello {name.title()}!")
    return render(request, "hello/greet.html",{
        "name":name.title()
    })

def index(request):
    #return HttpResponse("Hello World!") #这里直接返回了一个字符串的httpresponse
    return render(request,"hello/index.html")

def martin(request):
    return HttpResponse("Hello Martin!")

webprogramming/lecture3/lecture3/newyear/views.py
import datetime
from django.shortcuts import render



def index(request):
    now = datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "isNewYear": True
    })

webprogramming/lecture3/lecture3/tasks/views.py
from django.shortcuts import render

tasks = ["foo", "bar","baz"]

# Create your views here.


def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
        return render(request, "tasks/add.html", {
        "tasks": tasks
    })

webprogramming/lecture3/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Greet</title>
    </head>
    <body>
        <h1>
            Hello {{name}}!
        </h1>
    </body>
</html>

webprogramming/lecture3/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>
            Hello World!
        </h1>
    </body>
</html>

webprogramming/lecture3/lecture3/newyear/templates/newyear/index.html
{%load static%}


<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it new year?</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css'%}">
    </head>
    <body>
        {% if isNewYear%}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

webprogramming/lecture3/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1> Add task</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    <input type="text" name="task">
    <input type="submit">
</form>
<a href={% url 'tasks:index' %}>View Tasks</a>
{% endblock %}

webprogramming/lecture3/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
    <li>{{task}}</li>
    {% endfor %}
</ul>

<a href={% url 'tasks:add' %}>Add a New Task</a>
{% endblock %}

webprogramming/lecture3/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tasks</title>
</head>

<body>
    {% block body %}
    {% endblock %}
</body>

</html>